---
name: Push image to Docker Hub
on:
  release:
    types:
      - published

env:
  GH_TOKEN: ${{ secrets.token }}
  NAME: ${{ secrets.docker_username }}
  PASS: ${{ secrets.docker_password }}
  DISCORD: ${{ secrets.discord_webhook }}

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub CLI version
        id: ghcli
        run: |
          check=$(curl -s "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name":' | sed "s/[^0-9.]//g" | head -n1)
          echo ::set-output name=response::$check
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.NAME }}
          password: ${{ env.PASS }}
      - name: Build and push with tag ${{ steps.ghcli.outputs.response }}
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: moleszek/ghcli:${{ steps.ghcli.outputs.response }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: moleszek/ghcli:latest
  notify_on_success:
    name: Send notification on success
    needs:
      - build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully build and push docker image to DockerHub!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - build
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Failed to build and push docker image to DockerHub!"
