---
name: Check image
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
      - name: Test docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: false
          tags: ghcli:latest
