---
name: Check image
on:
  pull_request:
    types: [ opened, synchronize ]

env:
  GH_TOKEN: ${{ secrets.token }}

jobs:
  test:
    name: Test docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout version_checker repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ env.GH_TOKEN }}
      - name: Test docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: false
          tags: ghcli:latest
